### ISSUE TITLE
Inconsistent Z-layer of rendered tilemap

### ISSUE THREAD

**Issue by geirsagberg** [StarArawn/bevy_ecs_tilemap#308] opened 2022-10-08 10:33 UTC
I have a background image as `SpriteBundle`, a player character as a `SpriteSheetBundle` and the tiled map as a `TiledMapBundle`. I have adjusted the Z transform of the background image and the player so that the player is showing in front of the background. However, the tiled map sometimes shows behind the background, and sometimes in front:

![Screenshot 2022-10-08 122811](https://user-images.githubusercontent.com/594564/194703140-d9890125-405a-402c-94c2-87839e4fe5d5.png)
![Screenshot 2022-10-08 122848](https://user-images.githubusercontent.com/594564/194703144-7ef24e90-f57e-4cff-be7e-ef92f2ac4d27.png)

- It seems completely random, with roughly a 50%/50% chance of the tilemap platforms showing up or not.
- Adjusting the transform of the TiledMap has no effect

I do not quite understand the render pipeline of bevy_ecs_tilemap; how does it work? How can I ensure that the tilemap shows up in front of my background image?

My code is here: https://github.com/geirsagberg/rusted_chrome_2

**Comment by bzm3r** [comment] 2022-10-09 01:49
Hey, so this is an issue that is upstream, in `bevy`. It has been fixed on `bevy`'s main: https://github.com/bevyengine/bevy/pull/5942

See also related issue: https://github.com/bevyengine/bevy/issues/6048

As for solutions: I will make a branch of `bevy_ecs_tilemap` that depends on `bevy`'s main branch. Then, you can use this branch of `bevy_ecs_tilemap` in your work?

**Comment by geirsagberg** [comment] 2022-10-09 09:20
Excellent, thanks for the quick response :D And yes, a main-tracking branch would be sweet!

**Comment by StarArawn** [comment] 2022-10-09 15:49
> Excellent, thanks for the quick response :D And yes, a main-tracking branch would be sweet!

Done:
https://github.com/StarArawn/bevy_ecs_tilemap/pull/310

Note: Not all examples are working yet, but it should be tracking bevy main and we'll get the examples updated soon!

**Comment by StarArawn** [comment] 2022-10-12 18:16
@geirsagberg I'm marking this as closed since the issue is fixed in bevy main and we have a bevy-track branch. Please open a new issue if you think this is still a problem. 👍

**Closed by StarArawn** 2022-10-12 18:16 UTC
