### ISSUE TITLE
Newer `tiled` dependency planned?

### ISSUE THREAD

**Issue by Danl2620** [StarArawn/bevy_ecs_tilemap#320] opened 2022-10-24 01:10 UTC
Hi, I'm trying a custom map with the `tiled.rs` example but it throws this warning:

```
WARN bevy_asset::asset_server: encountered an error while loading an asset: Maps with external tilesets must know their file location.  See parse_with_path(Path).
```

I can't track down where that warning comes from but I'm guessing it's from the `tiled` crate dependency. That crate has made major changes to map loading since the pinned version used by `bevy_ecs_tiled` (0.9). I'm wondering if there's any plan or desire to upgrade to the latest version of `tiled` (0.10.2)?

**Comment by StarArawn** [comment] 2022-10-24 01:34
> I'm wondering if there's any plan or desire to upgrade to the latest version of tiled (0.10.2)?
No plan currently, but PR's for these types of things are always welcome. 👍

**Comment by Danl2620** [comment] 2022-10-29 00:21
Ok, sounds good. I'll take a look this weekend.

**Comment by bjorn** [comment] 2022-11-17 12:54
Duplicate of #249?

**Closed** 2023-01-13 05:03 UTC
Labels: enhancement
